name: TuSKe
description: A Skript Addon which has some managers, such as custom enchantments, recipes and GUI inventory, and some general stuffs.
main: me.tuke.sktuke.TuSKe
version: 1.8.1
author: Tuke_Nuke
website: github.com/Tuke-Nuke/TuSKe
softdepend: [Skript, SimpleClans, SimpleClansLegacy, Legendchat, Marriage, ProtocolSupport, ViaVersion, Landlord, Umbaska, SkQuery] #Last two dependencies are just to not register ClickType and InventoryType before them
commands:
  tuske:
    description: Main command for TuSKe
    usage: /tuske
    permission: tuske.admin
    permission-message: §cYou don't have permission for this command!
permissions:
  tuske.admin:
    description: Access to /tuske.
    default: op